// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsnzooxzamovffiqtgmv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzbnpvb3h6YW1vdmZmaXF0Z212Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMTExMjcsImV4cCI6MjA1OTU4NzEyN30.I0ByFCrm5fuRR1pZUZq475ggnghBIdExAMSNxBwoSHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);